# Generated by Django 6.0.6 on 2026-07-05 19:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('mrn', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='PEN', max_length=3)),
                ('findings', models.TextField()),
                ('conclusions', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('study_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accession_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_data.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id_study', models.AutoField(primary_key=True, serialize=False)),
                ('pacs_url', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField()),
                ('accession_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_data.patientprofile')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_data.report')),
                ('study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_data.studyrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='studyrequest',
            index=models.Index(fields=['accession_number'], name='idx_studyreq_accession'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['patient', 'date'], name='idx_study_patient_date'),
        ),
    ]
