# Generated by Django 6.0.6 on 2026-07-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='study',
            name='idx_study_patient_date',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, help_text='External patient identifier used for cross-clinic federation (CURP, MRN, etc.)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='study',
            name='modality',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='study_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='study',
            name='study_uid',
            field=models.CharField(blank=True, help_text='DICOM StudyInstanceUID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_data.studyrequest'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['patient', 'study_date'], name='idx_study_patient_date'),
        ),
        migrations.RemoveField(
            model_name='study',
            name='date',
        ),
    ]
