# Generated by Django 6.0.6 on 2026-07-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_data', '0002_remove_study_idx_study_patient_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrequest',
            name='patient',
        ),
        migrations.RemoveIndex(
            model_name='study',
            name='idx_study_patient_date',
        ),
        migrations.AddField(
            model_name='study',
            name='aros_patient_id',
            field=models.CharField(default='', help_text='UUID of the AROS User/Patient', max_length=255),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='aros_patient_id',
            field=models.CharField(default='', help_text='UUID of the AROS User/Patient', max_length=255),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['aros_patient_id', 'study_date'], name='idx_study_patient_date'),
        ),
        migrations.RemoveField(
            model_name='study',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
