# Generated by Django 6.0.1 on 2026-07-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_study_accession_number_study_raditech_visit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='raditech_visit_id',
        ),
    ]
