# Generated by Django 6.0.1 on 2026-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregistry',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text="Internal ALB/Peer2Peer URL of the clinic's API (e.g. http://10.0.1.5:8001)", max_length=500),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='webhook_secret',
            field=models.CharField(default='', help_text='HMAC SHA-256 shared secret for validating incoming webhooks from this clinic', max_length=255),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='has_consent',
            field=models.BooleanField(default=True, help_text='Whether the user currently has active consent for this clinic'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of consent revocation. Null if consent is still active.', null=True),
        ),
        migrations.AlterField(
            model_name='clinicregistry',
            name='public_key',
            field=models.TextField(blank=True, help_text='Public key for S2S JWT validation from this clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='consentrecord',
            unique_together={('user', 'clinic')},
        ),
    ]
