# Generated by Django 6.0.1 on 2026-07-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_clinicregistry_api_url_clinicregistry_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.roles'),
        ),
    ]
