# Generated by Django 6.0.1 on 2026-07-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregistry',
            name='primary_color',
            field=models.CharField(default='#0284c7', help_text="HEX color for the clinic's white-label UI", max_length=7),
        ),
    ]
