# Generated by Django 6.0.1 on 2026-08-26 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_patientdoctorconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregistry',
            name='address',
            field=models.CharField(blank=True, default='Av. Insurgentes Sur 123, Roma Norte, CDMX', help_text='Dirección física completa', max_length=500),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='email',
            field=models.EmailField(blank=True, default='contacto@clinica.com', help_text='Correo institucional', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='latitude',
            field=models.FloatField(default=19.4326, help_text='Latitud calculada para el mapa'),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='longitude',
            field=models.FloatField(default=-99.1332, help_text='Longitud calculada para el mapa'),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='opening_hours',
            field=models.CharField(blank=True, default='Lun - Vie: 07:00 - 20:00 | Sáb: 08:00 - 14:00', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='phone',
            field=models.CharField(blank=True, default='+52 55 1234 5678', help_text='Teléfono de atención', max_length=50),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, help_text='Calificación de la clínica (1.0 - 5.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='Especialidades médicas y estudios ofrecidos'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('cedula_profesional', models.CharField(blank=True, default='', help_text='Cédula profesional médica', max_length=100)),
                ('specialty', models.CharField(blank=True, default='Radiología General', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
