# Generated by Django 6.0.1 on 2026-08-26 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_clinicregistry_address_clinicregistry_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregistry',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total de calificaciones recibidas por pacientes'),
        ),
        migrations.AlterField(
            model_name='clinicregistry',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Calificación calculada de la clínica (1.0 - 5.0)', max_digits=3),
        ),
        migrations.CreateModel(
            name='ClinicRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=5, help_text='Puntaje de 1 a 5 estrellas')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='identity.clinicregistry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('clinic', 'patient')},
            },
        ),
    ]
