# Generated by Django 6.0.1 on 2026-08-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_clinicregistry_total_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.CharField(blank=True, default='Ninguna', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, default='O+', max_length=10),
        ),
    ]
