# Generated by Django 6.0.1 on 2026-08-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_patientprofile_allergies_patientprofile_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregistry',
            name='report_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración visual estructurada del membrete para reportes médicos PDF'),
        ),
    ]
