# Generated by Django 6.0.1 on 2026-08-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_clinicregistry_report_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Global profile picture', null=True, upload_to='avatars/'),
        ),
    ]
