# Generated by Django 6.0.1 on 2026-09-17 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_notes',
            field=models.TextField(blank=True, default='', help_text='Razón de rechazo o propuesta por la clínica'),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='clinicregistry',
            name='opening_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
