# Generated by Django 6.0.1 on 2026-09-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_appointment_clinic_notes_clinicregistry_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='identity.clinicregistry'),
        ),
    ]
