# Generated by Django 6.0.1 on 2026-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_staffprofile_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='proposed_by',
            field=models.CharField(blank=True, choices=[('CLINIC', 'Clinic'), ('PATIENT', 'Patient')], help_text='Indicates who made the last proposal', max_length=10, null=True),
        ),
    ]
