# Generated by Django 6.0.1 on 2026-07-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDashboard', '0005_patient_mrn_patient_raditech_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='raditech_patient_id',
        ),
    ]
